### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by netdrag** [Invertus/PrestaShop-ElasticSearch#14] opened 2016-10-27 10:55 UTC
There are no images in the search results. 
Please add this line to 
controllers/front/elasticsearch.php on line 143:

$row['id_image'] = $product['_source']['id_image'];
and the images get loaded.

**Comment by rokaszygmantas** [comment] 2016-10-27 11:16
Thanks for your help! Please don't hesitate to contribute with a pull request next time :)

**Comment by netdrag** [comment] 2016-10-27 11:21
I would like to... as soon I have the time to figure out how that works :)

**Comment by sarjon** [comment] 2016-10-27 14:55
Thanks for your help, the issue is fixed now.

**Closed** 2016-10-27 14:55 UTC
